# Generated by Django 4.2.25 on 2026-03-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profil_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('enseignant', 'Enseignant'), ('candidat', 'Candidat')], default='candidat', max_length=20),
        ),
    ]
