# Generated by Django 4.2.25 on 2026-03-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_choix_options_alter_question_options_and_more'),
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='examen',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='examens', to='questions.question'),
        ),
        migrations.AddField(
            model_name='examen',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', "Envoyé à l'admin"), ('valide', "Validé par l'admin")], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='examen',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
