# Generated by Django 4.2.25 on 2026-03-23 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examens', '0002_alter_examen_options_examen_questions_examen_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenEnCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.examen')),
            ],
            options={
                'unique_together': {('candidat', 'examen')},
            },
        ),
    ]
