# Generated by Django 4.2.25 on 2026-03-08 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('duree_minutes', models.PositiveIntegerField()),
                ('nombre_questions', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SessionConcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_session', models.CharField(max_length=100)),
                ('date_heure_debut', models.DateTimeField()),
                ('date_heure_fin', models.DateTimeField()),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concours.concours')),
            ],
        ),
        migrations.AddField(
            model_name='concours',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concours.module'),
        ),
    ]
