# Generated by Django 4.2.25 on 2026-03-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concours',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concours', to='concours.module'),
        ),
        migrations.AlterField(
            model_name='sessionconcours',
            name='concours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='concours.concours'),
        ),
    ]
