# Generated by Django 4.2.25 on 2026-03-12 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concours', '0002_alter_concours_module_alter_sessionconcours_concours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concours',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='sessionconcours',
            options={'ordering': ['-date_heure_debut']},
        ),
        migrations.AddField(
            model_name='concours',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concours_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concours',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='concours',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sessionconcours',
            name='date_lancement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionconcours',
            name='duree_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='sessionconcours',
            name='etat',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionconcours',
            name='examen_lance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionconcours',
            name='lance_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_lancees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='concours',
            name='duree_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='concours',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concours', to='concours.module'),
        ),
        migrations.AlterField(
            model_name='concours',
            name='nombre_questions',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='sessionconcours',
            name='nom_session',
            field=models.CharField(max_length=200),
        ),
    ]
